if(keyboard_check_pressed(ord('Z')))
{
    if(place_meeting(argument0.x,argument0.y,obj_hammer)){
        drag=true;
        obj_pickuphelper.currentobj2="obj_hammer";
    }
    if(place_meeting(argument0.x,argument0.y,obj_knife)){
        drag=true;
        obj_pickuphelper.currentobj2="obj_knife";
    }
    if(place_meeting(argument0.x,argument0.y,obj_squiggle)){
        drag=true;
        obj_pickuphelper.currentobj2="obj_squiggle";
    }
}

if(keyboard_check_released(ord('Z')))
{
    if(drag==true)
    {
        if(place_meeting(argument0.x,argument0.y,obj_shoe))
        {
            scr_checkifmatch();
        }
        drag=false;
        obj_pickuphelper.currentobj2="";
    }
}
